name: Publish

on:
    push:
        branches: [main]
        paths:
            - "domains/**"
            - ".github/workflows/publish.yml"
            - "dnsconfig.js"

    workflow_dispatch:

concurrency:
    group: ${{ github.ref }}-publish
    cancel-in-progress: false

jobs:
    dns:
        name: DNS
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - run: echo '{"cloudflare":{"TYPE":"CLOUDFLAREAPI","apitoken":"ndEzr-64V8_1ObL7fFkP6f00rwKFJ7c91DMKvmGG"}}' > ./creds.json

            - name: Publish
              uses: koenrh/dnscontrol-action@v3
              env:
                  CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
              with:
                  args: push
                  config_file: "dnsconfig.js"
