name: Raw API

on:
    push:
        branches: [main]
        paths:
            - "domains/*"
            - ".github/workflows/raw-api.yml"

    workflow_dispatch:

concurrency:
    group: ${{ github.ref }}-raw-api
    cancel-in-progress: true

jobs:
    update:
        name: Update
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/checkout@v4
              with:
                  repository: open-domains/raw
                  path: raw
                  token: ${{ secrets.BOT }}

            - uses: actions/setup-node@v4
              with:
                  node-version: latest

            - name: Update Data
              run: node raw/scripts/update.js

            - name: Commit
              uses: cpina/github-action-push-to-another-repository@main
              with:
                  source-directory: "raw"
                  destination-github-username: open-domains
                  destination-repository-name: raw
                  user-email: open-domains@win11react.com
                  user-name: OD-BOT
                  commit-message: "Update Data via open-domains/register"
              env:
                  API_TOKEN_GITHUB: ${{ secrets.BOT }}
